export const OLYMPUS_STORM_CONFIG={
  id:"olympus_storm",name:"OLYMPUS STORM",rows:5,reels:6,mechanic:"PAY ANYWHERE + OLYMPUS REELS + STICKY BONUS",feature:"STORM_FREE_SPINS",maxWin:5000,maxWinMultiplier:5000,volatility:"HIGH",
  symbols:["crown","hourglass","ring","goblet","gem_red","gem_purple","gem_yellow","gem_green","gem_blue","scatter","orb"],scatter:"scatter",olympusSymbol:"orb",
  weights:{crown:44,hourglass:54,ring:64,goblet:74,gem_red:104,gem_purple:116,gem_yellow:130,gem_green:145,gem_blue:158,scatter:15},
  bonusWeights:{crown:43,hourglass:52,ring:61,goblet:71,gem_red:101,gem_purple:113,gem_yellow:126,gem_green:140,gem_blue:152,scatter:11},
  paytable:{crown:{8:10,10:25,12:50},hourglass:{8:2.5,10:10,12:25},ring:{8:2,10:5,12:15},goblet:{8:1.5,10:2,12:12},gem_red:{8:1,10:1.5,12:10},gem_purple:{8:.8,10:1.2,12:8},gem_yellow:{8:.5,10:1,12:5},gem_green:{8:.4,10:.9,12:4},gem_blue:{8:.25,10:.75,12:2}},
  multiplierValues:[2,3,4,5,6,8,10,12,15,20,25,50,100,250,500],multiplierWeights:[190,150,130,112,90,72,58,42,34,28,20,10,5,2,1],
  olympusChanceBase:.0025,olympusChanceBonus:.015,freeSpins:15,retriggerSpins:5,bonusBuyCost:100,bonusBuyBoost:1.27,mathScale:2.6
};
const REGULAR=Object.keys(OLYMPUS_STORM_CONFIG.paytable);
export function createOlympusStormResult(bet,rng=secureRandom){bet=cleanBet(bet);const cap=bet*OLYMPUS_STORM_CONFIG.maxWinMultiplier,state=createState(false,rng),olympusReels=rollOlympusReels(false,rng,[]),initialGrid=gridWithOlympus(state,olympusReels),base=runTumbles(state,bet,{bonus:false,rng,olympusReels,maxPayout:cap}),scatterPositions=findPositions(base.finalGrid,"scatter"),scatterCount=scatterPositions.length,scatterPayout=Math.min(Math.max(0,cap-base.payout),Math.floor(bet*scatterFactor(scatterCount))),bonusTriggered=scatterCount>=4&&base.payout+scatterPayout<cap,bonus=bonusTriggered?createFreeSpins(bet,rng,Math.max(0,cap-base.payout-scatterPayout)):null,payout=Math.min(cap,base.payout+scatterPayout+Number(bonus?.payout||0));return {gameId:OLYMPUS_STORM_CONFIG.id,initialGrid,olympusReels,finalGrid:bonus?.finalGrid||base.finalGrid,cascades:base.cascades,scatterPositions,scatterCount,scatterPayout,anticipationReel:findAnticipationReel(initialGrid),basePayout:base.payout+scatterPayout,bonusTriggered,bonusType:bonusTriggered?"STORM_FREE_SPINS":null,freeSpinsAwarded:bonus?.frames?.length||0,bonus,payout,multiplier:round4(payout/bet),maxWinHit:payout>=cap};}
export function createOlympusStormBonusBuyResult(bet,rng=secureRandom){bet=cleanBet(bet);const cap=bet*OLYMPUS_STORM_CONFIG.maxWinMultiplier,state=createState(false,rng),forced=[[0,0],[1,2],[3,1],[5,4]];for(const [c,r] of forced)state[r][c]={symbol:"scatter"};const initialGrid=gridOf(state),scatterPositions=findPositions(initialGrid,"scatter"),featureBet=Math.max(1,Math.floor(bet*OLYMPUS_STORM_CONFIG.bonusBuyBoost)),bonus=createFreeSpins(featureBet,rng,cap),payout=Math.min(cap,bonus.payout);return {gameId:OLYMPUS_STORM_CONFIG.id,initialGrid,olympusReels:[],finalGrid:bonus.finalGrid||initialGrid,cascades:[],scatterPositions,scatterCount:scatterPositions.length,scatterPayout:0,anticipationReel:3,basePayout:0,bonusTriggered:true,bonusPurchased:true,bonusType:"STORM_FREE_SPINS",freeSpinsAwarded:bonus.frames.length,bonus,payout,multiplier:round4(payout/bet),maxWinHit:payout>=cap};}
export function createFreeSpins(bet,rng=secureRandom,maxPayout=Number.MAX_SAFE_INTEGER){const frames=[];let remaining=OLYMPUS_STORM_CONFIG.freeSpins,total=0,guard=0,stickyOlympus=[],finalGrid=null;while(remaining>0&&guard<40&&total<maxPayout){remaining--;guard++;const state=createState(true,rng),stickyBefore=stickyOlympus.map(x=>({...x})),newOlympus=rollOlympusReels(true,rng,stickyBefore),activeOlympus=mergeOlympus(stickyBefore,newOlympus),initialGrid=gridWithOlympus(state,activeOlympus),room=Math.max(0,maxPayout-total),seq=runTumbles(state,bet,{bonus:true,rng,olympusReels:activeOlympus,maxPayout:room}),scatterPositions=findPositions(seq.finalGrid,"scatter"),scatterCount=scatterPositions.length;stickyOlympus=activeOlympus;let retrigger=scatterCount>=3?OLYMPUS_STORM_CONFIG.retriggerSpins:0;if(retrigger){const frameRoom=Math.max(0,40-(frames.length+1)-remaining);retrigger=Math.min(retrigger,frameRoom);remaining+=retrigger;}total+=seq.payout;finalGrid=seq.finalGrid;frames.push({spin:frames.length+1,initialGrid,stickyBefore,newOlympus,activeOlympus,finalGrid:seq.finalGrid,cascades:seq.cascades,scatterPositions,scatterCount,anticipationReel:findAnticipationReel(initialGrid),startMultiplier:sumOlympus(stickyBefore),endMultiplier:sumOlympus(activeOlympus),retrigger,payout:seq.payout});}return {type:"FREE_SPINS",name:"STORM ASCENSION",frames,payout:Math.floor(total),totalSpins:frames.length,finalMultiplier:sumOlympus(stickyOlympus),finalGrid,stickyOlympus};}
export function runTumbles(startState,bet,{bonus=false,rng=secureRandom,olympusReels=[],maxPayout=Number.MAX_SAFE_INTEGER}={}){let current=cloneState(startState),paid=0;const cascades=[],active=normalizeOlympus(olympusReels),olympusTotal=sumOlympus(active);for(let tumble=0;tumble<12&&paid<maxPayout;tumble++){const plainGrid=gridOf(current),evaluation=evaluatePayAnywhere(plainGrid,bet,active);if(!evaluation.wins.length)break;const appliedMultiplier=active.length?Math.max(1,olympusTotal):1,rawPayout=evaluation.payout,multipliedRaw=evaluation.wins.reduce((s,w)=>s+Math.floor(w.amount*(w.usesOlympus?appliedMultiplier:1)),0),room=Math.max(0,maxPayout-paid),cascadePayout=Math.min(room,multipliedRaw),removed=uniquePositions(evaluation.wins.flatMap(w=>w.naturalPositions||[])),collapsed=collapseAndRefill(current,removed,active,bonus,rng);paid+=cascadePayout;cascades.push({index:tumble+1,wins:evaluation.wins,removed,drops:collapsed.drops,nextGrid:gridWithOlympus(collapsed.state,active),olympusReels:active,multiplier:appliedMultiplier,multiplierTotal:olympusTotal,rawPayout,payout:cascadePayout});current=collapsed.state;if(!removed.length)break;}return {cascades,finalGrid:bonus?gridWithOlympus(current,active):gridOf(current),payout:Math.floor(paid),olympusReels:active,multiplier:active.length?olympusTotal:1};}
export function evaluatePayAnywhere(grid,bet=1,olympusReels=[]){bet=cleanBet(bet);const active=normalizeOlympus(olympusReels),locked=new Set(active.map(x=>x.c)),wins=[];for(const symbol of REGULAR){const naturalPositions=findPositions(grid,symbol).filter(p=>!locked.has(p.c)),count=naturalPositions.length+active.length;if(count<8)continue;const table=OLYMPUS_STORM_CONFIG.paytable[symbol],factor=count>=12?table[12]:count>=10?table[10]:table[8],amount=Math.max(1,Math.floor(bet*factor*OLYMPUS_STORM_CONFIG.mathScale)),wildPositions=active.flatMap(x=>Array.from({length:OLYMPUS_STORM_CONFIG.rows},(_,r)=>({r,c:x.c})));wins.push({symbol,count,naturalCount:naturalPositions.length,factor,amount,naturalPositions,positions:uniquePositions([...naturalPositions,...wildPositions]),usesOlympus:active.length>0&&naturalPositions.length<8,olympusReels:active});}return {wins,payout:wins.reduce((s,w)=>s+w.amount,0)};}
export function createState(bonus=false,rng=secureRandom){const weights=bonus?OLYMPUS_STORM_CONFIG.bonusWeights:OLYMPUS_STORM_CONFIG.weights;return Array.from({length:OLYMPUS_STORM_CONFIG.rows},()=>Array.from({length:OLYMPUS_STORM_CONFIG.reels},()=>({symbol:weightedPick(weights,rng)})));}
export function rollOlympusReels(bonus=false,rng=secureRandom,locked=[]){const taken=new Set((locked||[]).map(x=>Number(x.c))),chance=bonus?OLYMPUS_STORM_CONFIG.olympusChanceBonus:OLYMPUS_STORM_CONFIG.olympusChanceBase,out=[];for(let c=0;c<OLYMPUS_STORM_CONFIG.reels;c++){if(taken.has(c))continue;if(rng()<chance)out.push({c,value:weightedMultiplier(rng)});}return out;}
function collapseAndRefill(state,removed,olympusReels,bonus,rng){const removeSet=new Set(removed.map(p=>`${p.r}:${p.c}`)),locked=new Set(normalizeOlympus(olympusReels).map(x=>x.c)),next=Array.from({length:OLYMPUS_STORM_CONFIG.rows},()=>Array(OLYMPUS_STORM_CONFIG.reels)),drops=[],weights=bonus?OLYMPUS_STORM_CONFIG.bonusWeights:OLYMPUS_STORM_CONFIG.weights;for(let c=0;c<OLYMPUS_STORM_CONFIG.reels;c++){if(locked.has(c)){for(let r=0;r<OLYMPUS_STORM_CONFIG.rows;r++)next[r][c]={...state[r][c]};continue;}const survivors=[];for(let r=OLYMPUS_STORM_CONFIG.rows-1;r>=0;r--)if(!removeSet.has(`${r}:${c}`))survivors.push({r,cell:{...state[r][c]}});let target=OLYMPUS_STORM_CONFIG.rows-1;for(const item of survivors){next[target][c]=item.cell;drops.push({from:{r:item.r,c},to:{r:target,c},symbol:item.cell.symbol,new:false});target--;}for(let r=target;r>=0;r--){const cell={symbol:weightedPick(weights,rng)};next[r][c]=cell;drops.push({from:null,to:{r,c},symbol:cell.symbol,new:true});}}return {state:next,drops};}
function weightedMultiplier(rng){const vals=OLYMPUS_STORM_CONFIG.multiplierValues,w=OLYMPUS_STORM_CONFIG.multiplierWeights,total=w.reduce((a,b)=>a+b,0);let n=rng()*total;for(let i=0;i<vals.length;i++){n-=w[i];if(n<0)return vals[i];}return vals.at(-1);}
function weightedPick(weights,rng){const entries=Object.entries(weights),total=entries.reduce((a,[,w])=>a+Number(w),0);let n=rng()*total;for(const [id,w] of entries){n-=Number(w);if(n<0)return id;}return entries.at(-1)[0];}
function normalizeOlympus(list=[]){const map=new Map();for(const x of list||[]){const c=Math.floor(Number(x?.c));if(c>=0&&c<OLYMPUS_STORM_CONFIG.reels&&!map.has(c))map.set(c,{c,value:Math.max(2,Math.floor(Number(x?.value)||2))});}return [...map.values()].sort((a,b)=>a.c-b.c);}
function mergeOlympus(a,b){return normalizeOlympus([...(a||[]),...(b||[])]);}function sumOlympus(list){return normalizeOlympus(list).reduce((s,x)=>s+x.value,0);}function gridWithOlympus(state,list=[]){const grid=gridOf(state);for(const x of normalizeOlympus(list))for(let r=0;r<OLYMPUS_STORM_CONFIG.rows;r++)grid[r][x.c]=OLYMPUS_STORM_CONFIG.olympusSymbol;return grid;}function gridOf(state){return state.map(row=>row.map(cell=>cell.symbol));}function cloneState(s){return s.map(row=>row.map(cell=>({...cell})));}
function findPositions(grid,symbol){const out=[];for(let r=0;r<grid.length;r++)for(let c=0;c<grid[r].length;c++)if(grid[r][c]===symbol)out.push({r,c});return out;}function findAnticipationReel(grid){let seen=0;for(let c=0;c<OLYMPUS_STORM_CONFIG.reels;c++){if(c>0&&seen>=3)return c;for(let r=0;r<OLYMPUS_STORM_CONFIG.rows;r++)if(grid[r][c]==="scatter")seen++;}return -1;}
function scatterFactor(n){return n>=6?100:n===5?5:n===4?3:0;}function uniquePositions(list){const map=new Map();for(const p of list||[])if(Number.isInteger(p?.r)&&Number.isInteger(p?.c))map.set(`${p.r}:${p.c}`,{r:p.r,c:p.c});return [...map.values()];}function cleanBet(v){return Math.max(1,Math.floor(Number(v)||1));}function secureRandom(){try{const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296;}catch{return Math.random();}}function round4(v){return Math.round((Number(v)||0)*10000)/10000;}
